apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: gengen
    role: monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gengen
        role: monitor
    spec:
      volumes:
      - name: gengen-build-data
        persistentVolumeClaim:
          claimName: gengen-build-data
      containers:
      - name: monitor
        image: polejniczak/gengen-monitor:latest
        imagePullPolicy: Always
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
        volumeMounts:
          - name: gengen-build-data
            mountPath: "/build_data"
            readOnly: true
        ports:
        - containerPort: 8080
