apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: gengen
    role: monitor
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gengen
    role: monitor
  type: LoadBalancer